server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: a6sdy2~W&A*(SJH#YTS*ASD*762
    key-alias: perobobbot
#  servlet:
#    context-path: /api
application:
  jwt:
    key: ashdj2yasd9a876

spring:
  flyway:
    locations: classpath:db/migration
  datasource:
    url: jdbc:h2:~/db/perobobbot;AUTO_SERVER=true
    username: botserver
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
logging:
  level:
    web: DEBUG
    org:
      springframework:
        context.annotation.ClassPathBeanDefinitionScanner: OFF
        security: DEBUG


