@startuml
'https://plantuml.com/sequence-diagram


autonumber

actor User

box "Perobobbot" #LightBlue
participant TwitchController
participant TwitchService
end box

box "Twitch" #9147FF
participant Twitch
end box

User -> TwitchController
activate TwitchController

TwitchController -> TwitchService
Activate TwitchService

TwitchService -> Twitch
Twitch -> TwitchService

TwitchService -> TwitchController
Deactivate TwitchService

TwitchController -> User
Deactivate TwitchController
@enduml
