ALTER TABLE PEROBOBBOT.CLIENT ALTER COLUMN PLATFORM VARCHAR(31);
ALTER TABLE PEROBOBBOT.CLIENT ALTER COLUMN PLATFORM SET NOT NULL;
ALTER TABLE PEROBOBBOT.CLIENT ADD COLUMN  BOT_TOKEN VARCHAR(255) NULL;
ALTER TABLE PEROBOBBOT.CLIENT DROP CONSTRAINT UK_5VCMDUCX1A00WDXF6GU7FK6US;

