@startuml
'https://plantuml.com/sequence-diagram

autonumber

!theme cyborg

Perobobbot -> Twitch: Demande de souscription (callback, condition, secret)
Twitch --> Perobobbot: Accusée de la demande

Twitch -> Perobobbot: Vérification du callback
Perobobbot -> Twitch: Validation de la vérification

@enduml
