@startuml

title OAuth Client Credential Flow
Bot -> Twitch: Authentication Request
note right
POST https://id.twitch.tv/oauth2/token
    ?client_id=<your client ID>
    &client_secret=<your client secret>
    &grant_type=client_credentials
    &scope=<space-separated list of scopes>
end note
Twitch --> Bot: Authentication Response
note left
{
  "access_token": "<user access token>",
  "refresh_token": "",
  "expires_in": <number of seconds until the token expires>,
  "scope": ["<your previously listed scope(s)>"],
  "token_type": "bearer"
}
end note

@enduml