INSERT INTO PUBLIC.ROLE (ID, VERSION, NAME) VALUES (1, 0, 'ADMINISTRATOR');
INSERT INTO PUBLIC.ROLE (ID, VERSION, NAME) VALUES (2, 0, 'TRUSTED_USER');
INSERT INTO PUBLIC.ROLE (ID, VERSION, NAME) VALUES (3, 0, 'STANDARD_USER');
INSERT INTO PUBLIC.ROLE (ID, VERSION, NAME) VALUES (4, 0, 'ANY_USER');

-- initial administrator user with admin as password.
INSERT INTO PUBLIC.USER (ID, VERSION, LOGIN,  JWT_CLAIM, PASSWORD) VALUES (4, 0, 'admin', 'D@I0ccyN1x62uxSC', '$2a$10$.leTdbci87PDIEl6Y9pgc.FY2KL4Avg./7DE9f0skycs.73U3WHim');

INSERT INTO PUBLIC.USER_ROLE (ROLE_ID, USER_ID) VALUES (1, 4);
