INSERT INTO PUBLIC.ROLE (ID, VERSION, NAME) VALUES (1, 0, 'USER');
INSERT INTO PUBLIC.ROLE (ID, VERSION, NAME) VALUES (2, 0, 'ADMIN');

-- initial administrator user with admin as password.
INSERT INTO PUBLIC.USER (ID, VERSION, LOGIN,  JWT_CLAIM, PASSWORD) VALUES (4, 0, 'admin', 'D@I0ccyN1x62uxSC', '$2a$10$GKZoi8rifwUGOMRswW4ygu6SU.X7A5YbO18eXs8Ch5pyUXo2E1fI..');

INSERT INTO PUBLIC.USER_ROLE (ID, VERSION, ROLE_ID, USER_ID) VALUES (5, 0, 2, 4);
